const usersSeed = [
  {
    "fullname": "John Doe",
    "username": "johndoe",
    "email": "johndoe@mail.com",
    "password": "11111",
    "long": 106.845130,
    "lat": -6.208763,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Jane Smith",
    "username": "janesmith",
    "email": "janesmith@mail.com",
    "password": "11111",
    "long": 107.619125,
    "lat": -6.917464,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Ahmad Abdullah",
    "username": "ahmadabdullah",
    "email": "ahmadabdullah@mail.com",
    "password": "11111",
    "long": 110.418812,
    "lat": -7.556578,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Siti Nurul",
    "username": "sitinurul",
    "email": "sitinurul@mail.com",
    "password": "11111",
    "long": 112.620516,
    "lat": -7.257472,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Budi Santoso",
    "username": "budisantoso",
    "email": "budisantoso@mail.com",
    "password": "11111",
    "long": 107.602807,
    "lat": -6.966700,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Rina Anggraeni",
    "username": "rinaanggraeni",
    "email": "rinaanggraeni@mail.com",
    "password": "11111",
    "long": 110.373283,
    "lat": -7.795579,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Fahmi Setiawan",
    "username": "fahmisetiawan",
    "email": "fahmisetiawan@mail.com",
    "password": "11111",
    "long": 106.827183,
    "lat": -6.208821,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Diana Kusuma",
    "username": "dianakusuma",
    "email": "dianakusuma@mail.com",
    "password": "11111",
    "long": 110.388062,
    "lat": -7.767580,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Rizki Pratama",
    "username": "rizkipratama",
    "email": "rizkipratama@mail.com",
    "password": "11111",
    "long": 112.751049,
    "lat": -7.274217,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "fullname": "Eva Widjaja",
    "username": "evawidjaja",
    "email": "evawidjaja@mail.com",
    "password": "11111",
    "long": 110.425628,
    "lat": -7.782889,
    "accountType": "regular",
    "createdAt": "",
    "updatedAt": ""
  }
];


const postsSeed = [
  {
    "name": "Mittens",
    "size": "small",
    "age": "kitten",
    "breed": "Maine Coon",
    "gender": "male",
    "color": "gray",
    "description": "Adorable and playful kitten with soft fur. Loves to cuddle.",
    "photo": ["https://example.com/mittens1.jpg", "https://example.com/mittens2.jpg"],
    "long": 106.845130,
    "lat": -6.208763,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Whiskers",
    "size": "medium",
    "age": "adult",
    "breed": "Siamese",
    "gender": "female",
    "color": "cream",
    "description": "Friendly and elegant Siamese cat looking for a new home.",
    "photo": ["https://example.com/whiskers1.jpg", "https://example.com/whiskers2.jpg"],
    "long": 107.619125,
    "lat": -6.917464,
    "status": "adopted",
    "statusPrice": "With Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Fluffy",
    "size": "big",
    "age": "old",
    "breed": "Persian",
    "gender": "male",
    "color": "white",
    "description": "Gentle and wise Persian cat seeking a quiet and loving retirement home.",
    "photo": ["https://example.com/fluffy1.jpg", "https://example.com/fluffy2.jpg"],
    "long": 110.418812,
    "lat": -7.556578,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Luna",
    "size": "medium",
    "age": "kitten",
    "breed": "British Shorthair",
    "gender": "female",
    "color": "blue",
    "description": "Playful and curious British Shorthair kitten with striking blue fur.",
    "photo": ["https://example.com/luna1.jpg", "https://example.com/luna2.jpg"],
    "long": 112.620516,
    "lat": -7.257472,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Leo",
    "size": "small",
    "age": "adult",
    "breed": "Bengal",
    "gender": "male",
    "color": "spotted",
    "description": "Energetic Bengal cat with beautiful spotted coat. Loves to play and climb.",
    "photo": ["https://example.com/leo1.jpg", "https://example.com/leo2.jpg"],
    "long": 107.602807,
    "lat": -6.966700,
    "status": "adopted",
    "statusPrice": "With Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Cleo",
    "size": "big",
    "age": "old",
    "breed": "Ragdoll",
    "gender": "female",
    "color": "seal point",
    "description": "Gentle and affectionate Ragdoll cat looking for a calm and loving home.",
    "photo": ["https://example.com/cleo1.jpg", "https://example.com/cleo2.jpg"],
    "long": 110.373283,
    "lat": -7.795579,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Sphinx",
    "size": "medium",
    "age": "kitten",
    "breed": "Sphynx",
    "gender": "male",
    "color": "pink",
    "description": "Adventurous and friendly Sphynx kitten with a unique hairless coat.",
    "photo": ["https://example.com/sphinx1.jpg", "https://example.com/sphinx2.jpg"],
    "long": 106.827183,
    "lat": -6.208821,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Misty",
    "size": "big",
    "age": "adult",
    "breed": "Abyssinian",
    "gender": "female",
    "color": "fawn",
    "description": "Graceful Abyssinian cat seeking a loving and active home.",
    "photo": ["https://example.com/misty1.jpg", "https://example.com/misty2.jpg"],
    "long": 110.388062,
    "lat": -7.767580,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Oreo",
    "size": "small",
    "age": "kitten",
    "breed": "Scottish Fold",
    "gender": "male",
    "color": "black and white",
    "description": "Adorable Scottish Fold kitten with distinctive folded ears. Loves to play with toys.",
    "photo": ["https://example.com/oreo1.jpg", "https://example.com/oreo2.jpg"],
    "long": 112.751049,
    "lat": -7.274217,
    "status": "adopted",
    "statusPrice": "With Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Nala",
    "size": "medium",
    "age": "adult",
    "breed": "Norwegian Forest Cat",
    "gender": "female",
    "color": "tabby",
    "description": "Sweet and majestic Norwegian Forest Cat looking for a warm and cozy home.",
    "photo": ["https://example.com/nala1.jpg", "https://example.com/nala2.jpg"],
    "long": 110.425628,
    "lat": -7.782889,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Siber",
    "size": "big",
    "age": "old",
    "breed": "Siberian",
    "gender": "male",
    "color": "brown",
    "description": "Gentle and fluffy Siberian cat seeking a peaceful retirement home.",
    "photo": ["https://example.com/siber1.jpg", "https://example.com/siber2.jpg"],
    "long": 106.845130,
    "lat": -6.208763,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Whiskey",
    "size": "medium",
    "age": "kitten",
    "breed": "Exotic Shorthair",
    "gender": "male",
    "color": "silver",
    "description": "Charming Exotic Shorthair kitten with a sleek silver coat. Loves to play and explore.",
    "photo": ["https://example.com/whiskey1.jpg", "https://example.com/whiskey2.jpg"],
    "long": 107.619125,
    "lat": -6.917464,
    "status": "adopted",
    "statusPrice": "With Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Muffin",
    "size": "small",
    "age": "adult",
    "breed": "Ragamuffin",
    "gender": "female",
    "color": "calico",
    "description": "Sweet and gentle Ragamuffin cat looking for a loving home. Enjoys quiet cuddle sessions.",
    "photo": ["https://example.com/muffin1.jpg", "https://example.com/muffin2.jpg"],
    "long": 110.418812,
    "lat": -7.556578,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Burmie",
    "size": "big",
    "age": "old",
    "breed": "Burmese",
    "gender": "male",
    "color": "champagne",
    "description": "Regal Burmese cat seeking a calm and comfortable retirement home.",
    "photo": ["https://example.com/burmie1.jpg", "https://example.com/burmie2.jpg"],
    "long": 112.620516,
    "lat": -7.257472,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Bluebell",
    "size": "medium",
    "age": "kitten",
    "breed": "Russian Blue",
    "gender": "female",
    "color": "blue",
    "description": "Gentle and shy Russian Blue kitten looking for a patient and loving home.",
    "photo": ["https://example.com/bluebell1.jpg", "https://example.com/bluebell2.jpg"],
    "long": 107.602807,
    "lat": -6.966700,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Lucky",
    "size": "big",
    "age": "adult",
    "breed": "Indonesian Domestic",
    "gender": "male",
    "color": "orange",
    "description": "Friendly and easygoing domestic cat looking for a forever home.",
    "photo": ["https://example.com/lucky1.jpg", "https://example.com/lucky2.jpg"],
    "long": 112.620516,
    "lat": -7.257472,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Coco",
    "size": "small",
    "age": "kitten",
    "breed": "Siamese",
    "gender": "female",
    "color": "chocolate",
    "description": "Adorable Siamese kitten with a sweet personality. Loves to be pampered.",
    "photo": ["https://example.com/coco1.jpg", "https://example.com/coco2.jpg"],
    "long": 107.602807,
    "lat": -6.966700,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Simba",
    "size": "medium",
    "age": "adult",
    "breed": "Persian",
    "gender": "male",
    "color": "golden",
    "description": "Majestic Persian cat with a luxurious golden coat. Enjoys lounging in the sun.",
    "photo": ["https://example.com/simba1.jpg", "https://example.com/simba2.jpg"],
    "long": 107.619125,
    "lat": -6.917464,
    "status": "adopted",
    "statusPrice": "With Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  },
  {
    "name": "Lulu",
    "size": "big",
    "age": "old",
    "breed": "Bengal",
    "gender": "female",
    "color": "marbled",
    "description": "Elegant Bengal cat with a stunning marbled coat. Seeks a quiet and loving home.",
    "photo": ["https://example.com/lulu1.jpg", "https://example.com/lulu2.jpg"],
    "long": 110.418812,
    "lat": -7.556578,
    "status": "available",
    "statusPrice": "Without Adoption Fee",
    "AdopterId": "",
    "PosterId": "",
    "createdAt": "",
    "updatedAt": ""
  }
];


module.exports = { usersSeed, postsSeed };